select * from Employee_Source
select * from Employee_Target  

--------------------------------------------------------------------------------

MERGE Employee_Target AS T
USING Employee_Source AS S
ON T.EMPLOYEE_ID = S.EMPLOYEE_ID

WHEN MATCHED THEN
UPDATE SET
T.FIRST_NAME = S.FIRST_NAME,
T.LAST_NAME = S.LAST_NAME,
T.SALARY = S.SALARY,
T.MANAGER_ID = S.MANAGER_ID,
T.DEPARTMENT_ID = S.DEPARTMENT_ID

WHEN NOT MATCHED BY TARGET THEN
INSERT(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,MANAGER_ID,DEPARTMENT_ID)
VALUES(S.EMPLOYEE_ID,S.FIRST_NAME,S.LAST_NAME,S.SALARY,S.MANAGER_ID,S.DEPARTMENT_ID)

WHEN NOT MATCHED BY SOURCE THEN
DELETE;

--------------------------------------------------------------------------------


MERGE Employee_Target AS T
USING Employee_Source AS S
ON T.EMPLOYEE_ID = S.EMPLOYEE_ID

WHEN MATCHED AND T.SALARY <> S.SALARY OR T.MANAGER_ID <> S.MANAGER_ID
THEN
UPDATE SET
T.FIRST_NAME = S.FIRST_NAME,
T.LAST_NAME = S.LAST_NAME,
T.SALARY = S.SALARY,
T.MANAGER_ID = S.MANAGER_ID,
T.DEPARTMENT_ID = S.DEPARTMENT_ID

WHEN NOT MATCHED BY TARGET THEN
INSERT(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,MANAGER_ID,DEPARTMENT_ID)
VALUES(S.EMPLOYEE_ID,S.FIRST_NAME,S.LAST_NAME,S.SALARY,S.MANAGER_ID,S.DEPARTMENT_ID);


