SELECT 123 AS col1, '123' as col2, GETDATE() AS col3, NULL AS col4 INTO data_type_casting;

SELECT '1' + 1 AS casting

-- CAST
SELECT EMPLOYEE_ID, CAST(EMPLOYEE_ID AS VARCHAR(10)) AS emp_id_cast INTO emp_casting FROM employees
SELECT CAST(12.5 AS INT)
SELECT CAST('Mar 15 2024 03:05:00:212PM' AS DATETIME)
SELECT CAST('Mar 15 2024 03:05:00:212PM' AS DATETIME2)
SELECT CAST(NULL AS DATETIME2)
SELECT CAST(NULL AS VARCHAR)
SELECT CAST('This is very big string. VARCHAR has default 30 CHAR as limit.' AS VARCHAR)
SELECT CAST('This is very big string. VARCHAR has default 30 CHAR as limit.' AS VARCHAR(90))

-- CONVERT
SELECT EMPLOYEE_ID, CONVERT(VARCHAR(10), EMPLOYEE_ID) AS emp_id_conert INTO emp_convert FROM employees
SELECT CONVERT(VARCHAR(30), GETDATE(), 100)
SELECT CONVERT(VARCHAR(30), GETDATE(), 101)
SELECT CONVERT(VARCHAR(30), GETDATE(), 102)
SELECT CONVERT(VARCHAR(30), GETDATE(), 103)
SELECT CONVERT(VARCHAR(30), GETDATE(), 104)
SELECT CONVERT(VARCHAR(30), GETDATE(), 105)

-- TRY_CAST
SELECT TRY_CAST('abc' AS INT)

-- TRY_CONVERT
SELECT TRY_CONVERT(INT, 'abc')

